openapi: 3.0.2

info:
  title: API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

paths:
  /job:
    get:
      parameters:
        - name: n
          in: query
          required: true
          schema:
            type: string
      summary: getFiboJokes
      operationId: getFiboJokes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WorkflowStarterLambdaHandler.Arn}/invocations"
        # uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WorkflowStarterLambdaHandler.Arn}/invocations
        passthroughBehavior: "when_no_match"
